### ISSUE TITLE
crm history refresh logs are dumped to stdout

### ISSUE THREAD

**Issue by dmuhamedagic** [krig/parallax#1]
When crmsh (with the current HEAD) history wants to refresh logs they show up on the stdout. It seems like that the on disk logs don't get updated. Not sure where's the problem: here, in crmsh, or in the interface between the two. This effectively breaks history.

**Comment by dmuhamedagic** [comment]
Some, not that revealing, debug output:

INFO: fetching new logs, please wait ...
DEBUG: updating /var/log/messages from sle12-a (pos 1509074)
DEBUG: updating /var/log/messages from sle12-c (pos 2020599)
DEBUG: Num transition msgs: 0
DEBUG: Num start transition msgs: 0
DEBUG: Num transition msgs: 0
DEBUG: Num start transition msgs: 0
DEBUG: opening log /var/cache/crm/history/live/sle12-a/ha-log.txt
DEBUG: opening log /var/cache/crm/history/live/sle12-c/ha-log.txt
DEBUG: seek Thu Apr 16 09:50:06 2015:start in /var/cache/crm/history/live/sle12-c/ha-log.txt
DEBUG: sought to Apr 16 09:45:27 sle12-c systemd[1]: pacemaker.service: Got notification message from PID 14014, but reception only permitted for main PID 1129 (121323)
DEBUG: seek Thu Apr 16 09:50:06 2015:start in /var/cache/crm/history/live/sle12-a/ha-log.txt
DEBUG: sought to Apr 16 09:45:17 sle12-a systemd[1]: pacemaker.service: Got notification message from PID 1732, but reception only permitted for main PID 1157 (135639)

**Comment by dmuhamedagic** [comment]
Update: The on-disk logs do get updated, hence it's just to prevent the logs being dumped to stdout too.

**Comment by dmuhamedagic** [comment]
Ugh. The new PE files are dumped to stdout as well. parallax does that by default?

**Comment by krig** [comment]
Huh. That's really bad. I haven't seen this happen. I'll investigate.

**Comment by krig** [comment]
My guess is that this is some mistake I made when adapting the crmsh interface to pssh to use parallax.

**Comment by krig** [comment]
Oddly enough, this doesn't happen to me when testing. How do you make this happen?

**Comment by krig** [comment]
I reproduced it now.

**Comment by krig** [comment]
OK, I found the problem. I had accidentally changed the default for storing output in memory buffers to true in parallax, so that crm_pssh called it with that option set.

The options for pssh/parallax are somewhat intersecting and ambiguous, it would probably be good to clean that up... it is not clear which combination of inline, inline_stdout and print_out will result in the output being printed or not.

**Comment by krig** [comment]
Thanks!
